Repository FerretDB/github-actions, pull requests merged in 2022-10, with the labels that each got.

#100 Use Go 1.19.2
  setup-go/action.yml
Labels: deps

#99 Add contributing guidelines
  CONTRIBUTING.md
  README.md
  Taskfile.yml
Labels: project

#102 Bump deps
  go.mod
  go.sum
  tools/go.mod
  tools/go.sum
Labels: deps

#104 Bump deps
  go.mod
  go.sum
Labels: deps

#105 Remove forked `golangci-lint`
  .golangci-new.yml
  linters/action.yml
  tools/go.mod
  tools/go.sum
Labels: code/chore

#107 Remove old hack for the `dance` repo
  extract-docker-tag/main.go
  extract-docker-tag/main_test.go
Labels: code/chore

#106 Use organization webhook to log Project v2 events
  org-webhook/main.go
  org-webhook/main_test.go
  org-webhook/testdata/projectv2-item-edited.json
Labels: code/feature, trust

#109 Add check for `Size` field
  CONTRIBUTING.md
  README.md
  conform-pr/main.go
  conform-pr/main_test.go
Labels: code/feature, trust

#113 Bump deps
  go.mod
  go.sum
  linters/action.yml
  tools/go.mod
  tools/go.sum
Labels: deps, trust
