Repository FerretDB/github-actions, pull requests merged in 2022-05, with the labels that each got.

#43 Rename PR verification action to "conform"
  .github/workflows/conform-pr.yml
  .github/workflows/pr-verification.yml
  README.md
  conform-pr/action.yml
  conform-pr/main.go
  conform-pr/main_test.go
  extract-docker-tag/action.yml
  linters/action.yml
  setup-go/action.yml
Labels: code/chore

#51 Ensure that `GOLANGCI_LINT_CACHE` is set
  .github/workflows/go.yml
  setup-go/main.go
Labels: code/enhancement

#54 Add PR body (description) check to the conform-pr github action
  conform-pr/main.go
  conform-pr/main_test.go
  testdata/pull_request_body_with_dot.json
  testdata/pull_request_title_with_dot_body_without_dot.json
Labels: code/feature

#55 Check that title matches `[a-zA-Z0-9]$` regular expression
  conform-pr/main.go
  conform-pr/main_test.go
Labels: code/enhancement
