Repository FerretDB/github-actions, pull requests merged in 2022-11, with the labels that each got.

#114 Bump Go version
  setup-go/action.yml
Labels: deps

#110 Check `Sprint` field in PR
  conform-pr/main.go
  conform-pr/main_test.go
  internal/graphql/pull_request.go
  internal/graphql/pull_request_test.go
Labels: trust

#115 Read organization members
  .github/workflows/conform-pr.yml
  conform-pr/main.go
  conform-pr/main_test.go
  detect-matching-pr/main.go
  go.mod
  go.sum
  internal/github.go
  internal/graphql/pull_request_test.go
  restart-pr-actions/main.go
Labels: code/feature, trust

#119 Bump deps
  go.mod
  go.sum
  tools/go.mod
  tools/go.sum
Labels: deps, trust

#121 Check that auto-merge is enabled
  conform-pr/main.go
  conform-pr/main_test.go
  internal/graphql/pull_request.go
  internal/graphql/pull_request_test.go
Labels: code/feature, trust

#122 Handle `no ci` label to prevent bogus auto-merges
  .github/workflows/conform-pr.yml
  conform-pr/main.go
Labels: code/bug, trust
