Repository FerretDB/github-actions, pull requests merged in 2023-02, with the labels that each got.

#133 Extract multiple docker tags
  extract-docker-tag/action.yml
  extract-docker-tag/main.go
  extract-docker-tag/main_test.go
Labels: code/feature

#134 Extract all Docker images
  extract-docker-tag/action.yml
  extract-docker-tag/main.go
  extract-docker-tag/main_test.go
  go.mod
  go.sum
  tools/go.mod
  tools/go.sum
Labels: code/feature, trust

#135 Bump Go to 1.19.6
  setup-go/action.yml
Labels: deps, trust

#138 Speed-up Go installation
  go.mod
  go.sum
  setup-go/action.yml
  setup-go/main.go
  tools/go.mod
  tools/go.sum
Labels: trust
