Repository FerretDB/github-actions, pull requests merged in 2024-12, with the labels that each got.

#306 Bump deps
  conform-pr/main.go
  detect-matching-pr/main.go
  go.mod
  go.sum
  internal/github.go
  restart-pr-actions/main.go
  tools/go.mod
  tools/go.sum
Labels: code/chore, trust

#307 Use Ubicloud cache when possible
  .github/workflows/conform-pr.yml
  .github/workflows/go.yml
  .github/workflows/setup-go.yml
  go.mod
  go.sum
  setup-go/action.yml
  tools/go.mod
  tools/go.sum
Labels: trust

#308 Use Ubicloud Transparent Cache instead of a separate step
  setup-go/action.yml
Labels: code/enhancement, trust
